Repository CS2103JAN2018-T16-B2/main, pull requests merged in 2018-03, with the labels that each got.

#34 [v1.2][T16-B2] Finishing the autocompletion and sending of emails
  build.gradle
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/commons/core/Mailer.java
  src/main/java/seedu/address/logic/Autocompleter.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/seedu/address/commons/core/MailerTest.java
  src/test/java/seedu/address/logic/AutocompleterTest.java
Labels: minor enhancement

#31 [v1.2][T16-B2] Filter by date and RouteOptimization
  src/main/java/seedu/address/logic/Autocompleter.java
  src/main/java/seedu/address/logic/GetDistance.java
  src/main/java/seedu/address/logic/RouteOptimization.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/person/DatePredicate.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/FilterCommandSystemTest.java
Labels: major enhancement, minor enhancement

#45 Handle NullPointerException on illegal exit
  src/main/java/seedu/address/ui/UiManager.java
  src/test/java/seedu/address/ui/UiManagerTest.java
Labels: bug, major enhancement, type.task

#110 Improve UI
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/resources/view/BrowserPanel.fxml
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/LoginPane.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/PigeonsLogoDigital.png
  src/main/resources/view/PigeonsLogoDigitalDark.png
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/default.html
Labels: enhancement, priority.high, type.task

#111 Annotate and update BrowserPanel
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/resources/view/BrowserPanel.fxml
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/LoginPane.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: bug, type.task
